-- ============================================================================
-- tab — Supabase schema source map
-- ============================================================================
-- The editable database contract is split into numbered files under:
--   supabase/sql/
--
-- The deployable baseline migration is generated from those files at:
--   supabase/migrations/20260518000000_baseline.sql
--
-- Common commands:
--   ./supabase/scripts/build_schema.sh --check   # verify generated baseline
--   ./supabase/scripts/build_schema.sh --write   # refresh generated baseline
--   ./supabase/scripts/recreate_db.sh            # destructive reset + apply
--
-- This file is intentionally small. Do not put schema DDL here; add or edit the
-- narrowest numbered file in supabase/sql/ instead.
-- ============================================================================
