#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SOURCE_DIR="$ROOT_DIR/supabase/sql"
BASELINE_FILE="$ROOT_DIR/supabase/migrations/20260518000000_baseline.sql"

usage() {
  cat <<'EOF'
Build or verify the generated Supabase baseline schema.

Usage:
  ./supabase/scripts/build_schema.sh --check
  ./supabase/scripts/build_schema.sh --write
  ./supabase/scripts/build_schema.sh --out PATH
  ./supabase/scripts/build_schema.sh --print

Behavior:
  - Source SQL lives in numbered files under supabase/sql/.
  - The baseline migration is generated from those files.
  - supabase/schema.sql is intentionally a short pointer, not the schema body.
EOF
}

collect_parts() {
  find "$SOURCE_DIR" -maxdepth 1 -type f -name '[0-9][0-9]_*.sql' | LC_ALL=C sort
}

generate_schema() {
  local parts=()
  local part
  while IFS= read -r part; do
    parts+=("$part")
  done < <(collect_parts)

  if [[ "${#parts[@]}" -eq 0 ]]; then
    echo "No SQL source parts found in $SOURCE_DIR" >&2
    return 1
  fi

  cat <<'EOF'
-- ============================================================================
-- tab — Supabase baseline schema
-- ============================================================================
-- Generated from supabase/sql/*.sql by ./supabase/scripts/build_schema.sh.
-- Do not edit this file directly; edit the numbered source files instead.
-- For post-launch changes, switch to versioned per-change migrations.
-- ============================================================================
EOF

  for part in "${parts[@]}"; do
    local name
    name="$(basename "$part")"
    printf '\n-- >>> BEGIN %s\n\n' "$name"
    cat "$part"
    printf '\n-- <<< END %s\n' "$name"
  done
}

mode=""
out_file=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check|--write|--print)
      [[ -z "$mode" ]] || { echo "Only one mode may be supplied" >&2; exit 2; }
      mode="$1"
      shift
      ;;
    --out)
      [[ -z "$mode" ]] || { echo "Only one mode may be supplied" >&2; exit 2; }
      [[ $# -ge 2 ]] || { echo "--out requires a path" >&2; exit 2; }
      mode="$1"
      out_file="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 2
      ;;
  esac
done

[[ -n "$mode" ]] || { usage >&2; exit 2; }

case "$mode" in
  --print)
    generate_schema
    ;;
  --out)
    mkdir -p "$(dirname "$out_file")"
    generate_schema > "$out_file"
    ;;
  --write)
    tmp_file="$(mktemp "$BASELINE_FILE.XXXXXX")"
    trap 'rm -f "$tmp_file"' EXIT
    generate_schema > "$tmp_file"
    mv "$tmp_file" "$BASELINE_FILE"
    trap - EXIT
    echo "[build-schema] wrote $BASELINE_FILE"
    ;;
  --check)
    tmp_file="$(mktemp)"
    trap 'rm -f "$tmp_file"' EXIT
    generate_schema > "$tmp_file"
    if ! cmp -s "$tmp_file" "$BASELINE_FILE"; then
      echo "[build-schema] baseline is stale: $BASELINE_FILE" >&2
      diff -u "$BASELINE_FILE" "$tmp_file" >&2 || true
      exit 1
    fi
    echo "[build-schema] baseline is up to date"
    ;;
esac
